
all:
	g++ -I /home/varadhan/boost-1.6/include/ -L /home/varadhan/boost-1.6/lib/ main.cpp OptionPrinter.cpp CustomOptionDescription.cpp -lboost_program_options -lboost_system  -lboost_regex -lboost_filesystem -o cmdopt

clean:
	rm -f cmdopt
